<div>
<h2>Roles of Language in Game Text</h2>
<h4>
<p>
In games and fiction, I have always found myself enraptured by deep, expansive worlds. By this, I do not necessarily mean complex plot or giant genealogical character trees, but the richness of their backdrop--the world they inhabit and its history. Two narratives that I admire that come to mind are the great lore of the Dark Souls series and the very "lived-in", but still cartoony world of the Venture Brothers. This is the kind of profundity I wanted to help craft for Third Age. My scope, as the editor, focuses my influence on the text; thus, it was my goal as a writer to express this deep world through the game's language. However, the challenge is that I must convey this richness while still maintaining a strong readability and coherence. And, on the flip side, as the editor, I'm responsible to the technical side of the text; the sterile, stripped away language that is, if anything, the player interacts with the greatest level. It is balancing these two widely different uses of language that is the challenge.
Text is the player's most visceral manifestation of the world (note: huge editor's bias here). Language is well-suited to this challenge, and as a reader you can be both audience and participant. If I can begin with a cliched thought: pictures tell a thousand words. These pictures or images on the cards act as a snapshot of the world. But text, and its meaning, can be ambiguous by nature. A reader has his or her own perceptions, the author's intentions, a word's inherent abstract meaning, and the context into which the text is presented, written, and read in. (Sorry, I realize this is beginning to sound like a literary theory paper.) But the words are required to do such simple things here: they tell you how to play; they are instructions. However, while these words serve such a sundry purpose, they are also great for telling such deep stories.
Depending on the role of the text on the card, different planning goes into the crafting of each. Thus, like any writer, I must operate in the bounds of whatever particular text I'm writing.
</p><p>
	Mechanics, by default, must be fairly removed from the rest of the card: this is the player's brass tacks of what the card means to them. Thus, consistent, careful, and sterile language is used. Consistency, I've learned, is key; consistency in word-choice and word-order. I have to define a syntactic system so that the players can become intimate with the patterns of different mechanics. By doing this, a writer gives the players the ability to predict and expect certain language and rules in certain mechanical situations, and I think this is the best way to get messages across.
For example, it eventually became clear we needed rules for how to phrase a situation where a criterion must be met before a resulting action could occur. At first pass, we had:
</p><p>

do [necessary action], then [resultant action]
</p><p>

This syntax, of course, is fine, but there was overlap (and thus ambiguity) between just wanting to use then as an adverb and wanting to express a necessary sequence of events. So, my solution was to create a unique syntax for this sequence; something that is reserved for our particular situation. When I write:
</p><p>
first [necessary action]; then [resultant action] 
</p><p>
I am setting up bounds in which these situations will occur consistently. Now, whenever a player reads "first", he or she knows that this is a condition, often a payment of some kind. I don't have to loquaciously re-explain that one must be done before the next. Now, this may seem very obvious. It is, really. 
You want players to have instructions in the most digestible format as possible so they can focus on what's important: the intricacies of the particular card. This, when written properly, should read more like programming code than storytelling. Therefore, you get a card like this:
 </p><p>

	However, you can see how this does not lend itself to any story telling whatsoever. In the card names and flavor, I have much, much more room to play. Yet, I have just as great a task: I need to succinctly tell stories in small spaces, sometimes just single words. My first goal to create some depth to the world was to try to delineate the factions more subtly. 
To achieve this, I tried to use large language distinctions specific to each faction. For example, the Aristocracy uses Germanic and Old English influenced words. The Breakers use Romance influenced words (with some Greek). The idea is, even with little linguistic or etymological knowledge, any native English speaker can make a distinction between a very English word (where we get our hearty words) and a French-influenced word (like legerdemain, as an example--how is that actually a thing in English?). So where the Breakers might have, say, a weapon called "the Sanguine Bardiche" (using lofty, illustrious words), the Aristocrats would wield the "Meat Cleaver" (using strong, earthy words). The Denizens? Maybe "Cow Poke," or something. Do you see how there's a difference, even though we're describing, presumably, the same item? I wanted the different factions to intrinsically leave a different taste in our mouths when we read them--different themes residing in the language itself. But, that's ultimately not for me to decide. That's for you to judge; that was simply my attempt.
	</p><p>
	Above all else, flavor text is a great tool for explaining the world; this is another "snapshot" akin to the card's artwork. Excerpts, dialogue, or descriptions tell parts and fragments of a grander story. I like to think of it as a piece of a puzzle. While mundane descriptions can serve a purpose here, they do little to foster any sense of realness for the text. You want lore that the participate has to work for--learn, discover, and question. There is no certainty in history, so why present a fantasy world in such certitude?
	The goal of this erudite story-weaving is to communicate to the audience, but to tread the line of just affirming notions of the world. As /u/FlawedRed writes about the often obscured lore of Dark Souls, "[the writers] want to offer a unique experience that, frankly, doesn't care if the player might actually have to struggle a little and think or relinquish just a little control or comfort in the process." I think there's a lot of reward to trying to decipher a story like this. And even if that's not your bag, then at the very least, it strengthens the Third Age world to have this consistency and thought behind it.
	Now, I realize we're not the first to do this--not by a long shot. Magic: the Gathering, the progenitor of flavor text on card games, has utilized it for decades. But Third Age is much smaller scale. It would be easy to name-drop, to tell a linear story. As of right now, we have maybe a couple dozen characters; it would be simple to just say something simple about a character and not tie any other characters, events, or factions into it. But I tried not to do this, at least not straightaway.
	The universal cards I am most proud of. The flavor text there gives examples of my favorites: historical excerpts, nameless quotes, letters. You get a piece of the puzzle from every angle: the card name, the artwork, and the flavor text. We don't just come out and say it. You can probably figure out what's happening and what's happened, but we try to be coy about it.
	This is a challenge I've learned about as I've faced it. I've enjoyed the challenge, immensely. In sum, language is a great tool for story-telling (the oldest, in fact). I just hope I've done it some justice in my role as editor. Whether it's the mechanical text, card names, or flavor text, I've tried to insert some cleverness into weaving an enjoyable and rich story, like those of the games and books I've long admired. I'm not writing Game of Thrones here, but damnit I'm trying!

</p></h4>
</div>